### ISSUE TITLE
ImportError and data_dump_handler

### ISSUE THREAD

**Issue by JBrakefield** [Ladvien/arduino_ble_sense#1]
Edit: I also don't see selected_device = [] referenced anywhere else in the code. Was this intended to be where you put the mac address?

I get the following error when I try to run the code (after installing 'typing' using pip):
`ImportError: cannot import name 'Anypip' from 'typing'` - any thoughts on this?

I'm also trying to understand how the data_dump_handler works, but I can't find its actual definition. I see it referred to, but no code on what it actually does included in the script. I'm interested because I've been trying to write a BLE program and I'm having issues with receiving text data from the BLE device when it sends more than one line or chunk (and when that line/chunk exceeds 20 characters).

Any help would be greatly appreciated.

**Comment by Ladvien** [comment]
Hello @JBrakefield,

I've been pretty busy at the day job, so don't have time to dig in yet. But a couple thoughts:

I wrote a couple of blog articles on this project:
https://ladvien.com/arduino-nano-33-bluetooth-low-energy-setup/
https://ladvien.com/python-serial-terminal-with-arduino-and-bleak/

And regarding the 20 bytes. I believe this is the maximum data packet length for some BLE protocols:
> In a forthcoming blog post, we will go in depth about the BLE packet structure and the possible sizes of application data in a packet, but for now it is safe to say that a BLE packet contains a maximum of 20 bytes of application data for BLE v4.0 and v4.1 (v4.2 includes a data packet length extension, but this is not used in iOS or Android yet). Remember the actual BLE packet is longer in size but naturally it includes segments for many important purposes such as CRC and headers for different layers.

https://punchthrough.com/maximizing-ble-throughput-on-ios-and-android/

I've personally found most higher level frameworks will fire their callbacks when 20 bytes have been received.  At least, I found this true when working with CC254x based Bluetooth modules such as the HM-10 / 11 and BLE stacks in C#, JavaScript and iOS. In each of these cases, I had to solve the problem by reserving bytes for signaling the end of traffic (e.g., `\0` or `\n\r`, etc). This puts the burden on buffering the incoming data on your code, but that's pretty common.

I hope to have more time to respond proper, but hopefully this keeps you going.
